# #
#   @parent     : github workflow
#   @desc       : auto-assign a github issue to repository owner
#   @author     : Aetherinox
#   @url        : https://github.com/Aetherinox
# #

name: "🪪 Issues › Auto Assign"
run-name: "🪪 Worker › Auto Assign"

# #
#   triggers
# #

on:
    issues:
        types: [opened]
    pull_request:
        types: [opened]

# #
#   environment variables
# #

env:
  BOT_NAME_1:             AdminServ
  BOT_NAME_2:             AdminServX
  BOT_NAME_3:             EuropaServ
  BOT_NAME_DEPENDABOT:    dependabot[bot]

# #
#   jobs
# #

jobs:

    # #
    #   JOB > ASSIGN
    # #

    job-assign:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        environment:
            name: Orion
        steps:

            # #
            #   ASSIGN
            # #

            - name: >-
                  🏷️ Assign Assignee › ${{ github.repository_owner }}
              uses: pozil/auto-assign-issue@v2
              with:
                  repo-token: ${{ secrets.SELF_TOKEN_CL }}
                  assignees: ${{ github.repository_owner }}
                  numOfAssignee: 1
